Repository Magickbase/godwoken-explorer-ui, pull requests merged in 2022-11, with the labels that each got.

#689 fix: revoke button `connect + switch network + send tx` one click flow
  components/TokenApprovalList/RevokeButton.tsx
  public/locales/en-US/list.json
  public/locales/zh-CN/list.json
Labels: bug

#686 Display ERC 721/1155 transfers in a specific transaction
  components/BaseTransferlist/index.tsx
  components/BaseTransferlist/styles.module.scss
  components/CommonERCTransferlist/index.tsx
  cypress/integration/tx/index.spec.ts
  pages/tx/[hash].tsx
  public/locales/en-US/tx.json
  public/locales/zh-CN/tx.json
Labels: enhancement

#698 Fix: Read metadata of ERC 721/1155 from backend API
  components/MultiTokenActivityList/index.tsx
  components/MultiTokenInventoryList/index.tsx
  pages/multi-token-item/[...id].tsx
Labels: Fix

#726 Fix: wrapped label and the basic info width
  components/AccountOverview/index.tsx
  components/AccountOverview/styles.module.scss
  pages/token/[id].tsx
  pages/token/styles.module.scss
Labels: Fix

#684 fix: keep search text
  components/Search.tsx
  cypress/integration/search/index.spec.ts
  utils/handler.ts
Labels: bug

#739 Fix: Token item link in erc 1155 transfers is incorrect.
  components/BaseTransferlist/index.tsx
  components/CommonERCTransferlist/index.tsx
  pages/multi-token-item/[...id].tsx
  pages/tx/[hash].tsx
Labels: Fix

#725 feat: add official site on erc 721/1155 pages
  pages/multi-token-collection/[address].tsx
  pages/multi-token-collection/styles.module.scss
  pages/nft-collection/[address].tsx
  pages/nft-collection/styles.module.scss
  public/locales/en-US/multi-token.json
  public/locales/en-US/nft.json
  public/locales/zh-CN/multi-token.json
  public/locales/zh-CN/nft.json
Labels: enhancement

#727 Fix: Truncated field misses ellipsis and label is wrapped
  components/AccountOverview/index.tsx
  components/AccountOverview/styles.module.scss
  components/InfoList/index.tsx
  components/InfoList/styles.module.scss
  components/SmartContractInfo/index.tsx
  components/SmartContractInfo/styles.module.scss
Labels: Fix

#733 feat: hidden token field if contract is not token contract
  components/SmartContractInfo/index.tsx
Labels: enhancement
