Repository Magickbase/godwoken-explorer-ui, pull requests merged in 2022-12, with the labels that each got.

#757 fix: i18n for import token title
  pages/token/[id].tsx
  pages/token/styles.module.scss
Labels: bug

#752 Fix: optimize displayed on the transaction info and token pages.
  pages/token/[id].tsx
  pages/token/styles.module.scss
  pages/tx/[hash].tsx
  pages/tx/styles.module.scss
Labels: Fix

#736 Feat: change the pagination to cursor and add sorter --- Bridge Token and Layer 2 Native Token
  pages/tokens/[type].tsx
  pages/tokens/styles.module.scss
Labels: Feat
